# Generated by Django 4.2.13 on 2024-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_buyer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_freelancer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
